<?php
$currency_sql="INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (1, 'Mauritania', 'MR', 'Mauritanian Ouguiya', '', '', 'MRO', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (2, 'Martinique (French)', 'MQ', 'Euro', '€', '&#8364;', 'EUR', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (3, 'Malta', 'MT', 'Maltese Lira', '', '', 'MTL', '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (4, 'Marshall Islands', 'MH', 'US Dollar', '$', '&#036;', 'USD', '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (5, 'Mali', 'ML', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (6, 'Maldives', 'MV', 'Maldive Rufiyaa', '', '', 'MVR', '0', '0' , 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (7, 'Malaysia', 'MY', 'Malaysian Ringgit', '', '', 'MYR', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (8, 'Malawi', 'MW', 'Malawi Kwacha', '', '', 'MWK', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (9, 'Madagascar', 'MG', 'Malagasy Franc', '', '', 'MGF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (10, 'Macau', 'MO', 'Macau Pataca', '', '', 'MOP', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (11, 'Macedonia', 'MK', 'Denar', '', '', 'MKD', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (12, 'Luxembourg', 'LU', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (13, 'Lithuania', 'LT', 'Lithuanian Litas', '', '', 'LTL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (14, 'Liechtenstein', 'LI', 'Swiss Franc', '', '', 'CHF', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (15, 'Libya', 'LY', 'Libyan Dinar', '', '', 'LYD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (16, 'Liberia', 'LR', 'Liberian Dollar', '$', '&#036;', 'LRD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (17, 'Lesotho', 'LS', 'Lesotho Loti', '', '', 'LSL', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (18, 'Lebanon', 'LB', 'Lebanese Pound', '', '', 'LBP', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (19, 'Latvia', 'LV', 'Latvian Lats', '', '', 'LVL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (20, 'Laos', 'LA', 'Lao Kip', '', '', 'LAK', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (21, 'Kyrgyzstan', 'KG', 'Som', '', '', 'KGS', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (22, 'Kuwait', 'KW', 'Kuwaiti Dinar', '', '', 'KWD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (23, 'Korea, South', 'KR', 'Korean Won', '', '', 'KRW', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (24, 'Korea, North', 'KP', 'North Korean Won', '', '', 'KPW', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (25, 'Kiribati', 'KI', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (26, 'Kenya', 'KE', 'Kenyan Shilling', '', '', 'KES', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (27, 'Kazakhstan', 'KZ', 'Kazakhstan Tenge', '', '', 'KZT', '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (28, 'Jordan', 'JO', 'Jordanian Dinar', '', '', 'JOD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (29, 'Jersey', 'JE', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (30, 'Japan', 'JP', 'Japanese Yen', '¥', '&#165;', 'JPY', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (31, 'Jamaica', 'JM', 'Jamaican Dollar', '$', '&#036;', 'JMD', '0', '0' ,'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (32, 'Ivory Coast', 'CI', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (33, 'Italy', 'IT', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (34, 'Isle of Man', 'IM', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (35, 'Israel', 'IL', 'Israeli New Shekel', '', '', 'ILS', '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (36, 'Ireland', 'IE', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (37, 'Iraq', 'IQ', 'Iraqi Dinar', '', '', 'IQD', '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (38, 'Indonesia', 'ID', 'Indonesian Rupiah', '', '', 'IDR', '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (39, 'Iran', 'IR', 'Iranian Rial', '', '', 'IRR', '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (40, 'India', 'IN', 'Indian Rupee', '', '', 'INR', '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (41, 'Iceland', 'IS', 'Iceland Krona', '', '', 'ISK', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (42, 'Hungary', 'HU', 'Hungarian Forint', '', '', 'HUF', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (43, 'Hong Kong', 'HK', 'Hong Kong Dollar', '$', '&#036;', 'HKD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (44, 'Honduras', 'HN', 'Honduran Lempira', '', '', 'HNL', '0', '0' , 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (45, 'Heard Island and McDonald Islands', 'HM', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (46, 'Haiti', 'HT', 'Haitian Gourde', '', '', 'HTG', '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (47, 'Guyana', 'GY', 'Guyana Dollar', '$', '&#036;', 'GYD', '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (48, 'Guinea Bissau', 'GW', 'Guinea-Bissau Peso', '', '', 'GWP', '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (49, 'Guinea', 'GN', 'Guinea Franc', '', '', 'GNF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (50, 'Guernsey', 'GF', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (51, 'Guatemala', 'GT', 'Guatemalan Quetzal', '', '', 'QTQ', '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (52, 'Guam (USA)', 'GU', 'US Dollar', '$', '&#036;', 'USD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (53, 'Grenada', 'GD', 'East Carribean Dollar', '$', '&#036;', 'XCD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (54, 'Guadeloupe (French)', 'GP', 'Euro', '€', '&#8364;', 'EUR', '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (55, 'Greenland', 'GL', 'Danish Krone', '', '', 'DKK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (56, 'Greece', 'GR', 'Euro', '€', '&#8364;', 'EUR', '0', '19','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (57, 'Gibraltar', 'GI', 'Gibraltar Pound', '', '', 'GIP', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (58, 'Ghana', 'GH', 'Ghanaian Cedi', '', '', 'GHC', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (59, 'Germany', 'DE', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (60, 'Georgia', 'GE', 'Georgian Lari', '', '', 'GEL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (61, 'Gambia', 'GM', 'Gambian Dalasi', '', '', 'GMD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (62, 'Gabon', 'GA', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (63, 'French Southern Territories', 'TF', 'Euro', '€', '&#8364;', 'EUR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (64, 'France', 'FR', 'Euro', '€', '&#8364;', 'EUR', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (65, 'Finland', 'FI', 'Euro', '€', '&#8364;', 'EUR', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (66, 'Fiji', 'FJ', 'Fiji Dollar', '$', '&#036;', 'FJD', '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (67, 'Faroe Islands', 'FO', 'Danish Krone', '', '', 'DKK', '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (68, 'Falkland Islands', 'FK', 'Falkland Islands Pound', '', '', 'FKP', '0', '0' ,'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (69, 'Ethiopia', 'ET', 'Ethiopian Birr', '', '', 'ETB', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (70, 'Estonia', 'EE', 'Estonian Kroon', '', '', 'EEK', '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (71, 'Eritrea', 'ER', 'Eritrean Nakfa', '', '', 'ERN', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (72, 'Equatorial Guinea', 'GQ', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (73, 'El Salvador', 'SV', 'El Salvador Colon', '', '', 'SVC', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (74, 'Egypt', 'EG', 'Egyptian Pound', '', '', 'EGP', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (75, 'Ecuador', 'EC', 'Ecuador Sucre', '', '', 'ECS', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (76, 'East Timor', 'TP', 'Timor Escudo', '', '', 'TPE', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (77, 'Dominican Republic', 'DO', 'Dominican Peso', '', '', 'DOP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (78, 'Dominica', 'DM', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (79, 'Djibouti', 'DJ', 'Djibouti Franc', '', '', 'DJF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (80, 'Denmark', 'DK', 'Danish Krone', '', '', 'DKK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (81, 'Democratic Republic of Congo', 'CD', 'Francs', '', '', 'CDF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (82, 'Czech Rep.', 'CZ', 'Czech Koruna', '', '', 'CZK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (83, 'Cyprus', 'CY', 'Cyprus Pound', '', '', 'CYP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (84, 'Cuba', 'CU', 'Cuban Peso', '', '', 'CUP', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (85, 'Croatia', 'HR', 'Croatian Kuna', '', '', 'HRK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (86, 'Costa Rica', 'CR', 'Costa Rican Colon', '', '', 'CRC', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (87, 'Cook Islands', 'CK', 'New Zealand Dollar', '$', '&#036;', 'NZD', '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (88, 'Congo', 'CG', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (89, 'Comoros', 'KM', 'Comoros Franc', '', '', 'KMF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (90, 'Colombia', 'CO', 'Colombian Peso', '', '', 'COP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (91, 'Cocos (Keeling) Islands', 'CC', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (92, 'Christmas Island', 'CX', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (93, 'Chile', 'CL', 'Chilean Peso', '', '', 'CLP', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (94, 'China', 'CN', 'Yuan Renminbi', '', '', 'CNY', '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (95, 'Chad', 'TD', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (96, 'Central African Republic', 'CF', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (97, 'Cayman Islands', 'KY', 'Cayman Islands Dollar', '$', '&#036;', 'KYD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (98, 'Cape Verde', 'CV', 'Cape Verde Escudo', '', '', 'CVE', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (99, 'Cameroon', 'CM', 'CFA Franc BEAC', '', '', 'XAF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (100, 'Canada', 'CA', 'Canadian Dollar', '$', '&#036;', 'CAD', '1', '','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (101, 'Cambodia', 'KH', 'Kampuchean Riel', '', '', 'KHR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (102, 'Burundi', 'BI', 'Burundi Franc', '', '', 'BIF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (103, 'Burkina Faso', 'BF', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (104, 'Bulgaria', 'BG', 'Bulgarian Lev', '', '', 'BGL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (105, 'Brunei Darussalam', 'BN', 'Brunei Dollar', '$', '&#036;', 'BND', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (106, 'British Indian Ocean Territory', 'IO', 'US Dollar', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (107, 'Brazil', 'BR', 'Brazilian Real', '', '', 'BRL', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (108, 'Bouvet Island', 'BV', 'Norwegian Krone', '', '', 'NOK', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (109, 'Botswana', 'BW', 'Botswana Pula', '', '', 'BWP', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (110, 'Bosnia-Herzegovina', 'BA', 'Marka', '', '', 'BAM', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (111, 'Bolivia', 'BO', 'Boliviano', '', '', 'BOB', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (112, 'Bhutan', 'BT', 'Bhutan Ngultrum', '', '', 'BTN', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (113, 'Bermuda', 'BM', 'Bermudian Dollar', '$', '&#036;', 'BMD', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (114, 'Benin', 'BJ', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (115, 'Belize', 'BZ', 'Belize Dollar', '$', '&#036;', 'BZD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (116, 'Belgium', 'BE', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (117, 'Belarus', 'BY', 'Belarussian Ruble', '', '', 'BYB', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (118, 'Barbados', 'BB', 'Barbados Dollar', '$', '&#036;', 'BBD', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (119, 'Bangladesh', 'BD', 'Bangladeshi Taka', '', '', 'BDT', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (120, 'Bahrain', 'BH', 'Bahraini Dinar', '', '', 'BHD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (121, 'Bahamas', 'BS', 'Bahamian Dollar', '$', '&#036;', 'BSD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (122, 'Azerbaijan', 'AZ', 'Azerbaijanian Manat', '', '', 'AZM', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (123, 'Austria', 'AT', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (124, 'Aruba', 'AW', 'Aruban Guilder', '', '', 'AWG', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (125, 'Armenia', 'AM', 'Armenian Dram', '', '', 'AMD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (126, 'Argentina', 'AR', 'Argentine Peso', '', '', 'ARS', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (127, 'Antigua and Barbuda', 'AG', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (128, 'Antarctica', 'AQ', 'Dollar', '$', '&#036;', 'ATA', '0', '0','antarctica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (129, 'Anguilla', 'AI', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (130, 'Angola', 'AO', 'Angolan New Kwanza', '', '', 'AON', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (131, 'Andorra', 'AD', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (132, 'American Samoa', 'AS', 'US Dollar', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (133, 'Algeria', 'DZ', 'Algerian Dinar', '', '', 'DZD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (134, 'Albania', 'AL', 'Albanian Lek', '', '', 'ALL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (135, 'Afghanistan', 'AF', 'Afghanistan Afghani', '', '', 'AFA', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (136, 'USA', 'US', 'US Dollar', '$', '&#036;', 'USD', '1', '','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (137, 'Australia', 'AU', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (138, 'Great Britain', 'GB', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (139, 'Mauritius', 'MU', 'Mauritius Rupee', '', '', 'MUR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (140, 'Mayotte', 'YT', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (141, 'Mexico', 'MX', 'Mexican Nuevo Peso', '', '', 'MXN', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (142, 'Micronesia', 'FM', 'US Dollar', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (143, 'Moldova', 'MD', 'Moldovan Leu', '', '', 'MDL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (144, 'Monaco', 'MC', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (145, 'Mongolia', 'MN', 'Mongolian Tugrik', '', '', 'MNT', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (146, 'Montserrat', 'MS', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (147, 'Morocco', 'MA', 'Moroccan Dirham', '', '', 'MAD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (148, 'Mozambique', 'MZ', 'Mozambique Metical', '', '', 'MZM', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (149, 'Myanmar', 'MM', 'Myanmar Kyat', '', '', 'MMK', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (150, 'Namibia', 'NA', 'Namibian Dollar', '$', '&#036;', 'NAD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (151, 'Nauru', 'NR', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (152, 'Nepal', 'NP', 'Nepalese Rupee', '', '', 'NPR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (153, 'Netherlands', 'NL', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (154, 'Netherlands Antilles', 'AN', 'Netherlands Antillean Guilder', '', '', 'ANG', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (155, 'New Caledonia (French)', 'NC', 'CFP Franc', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (156, 'New Zealand', 'NZ', 'New Zealand Dollar', '$', '&#036;', 'NZD', '0', '12.5','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (157, 'Nicaragua', 'NI', 'Nicaraguan Cordoba Oro', '', '', 'NIC', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (158, 'Niger', 'NE', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (159, 'Nigeria', 'NG', 'Nigerian Naira', '', '', 'NGN', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (160, 'Niue', 'NU', 'New Zealand Dollar', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (161, 'Norfolk Island', 'NF', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (162, 'Northern Mariana Islands', 'MP', 'US Dollar', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (163, 'Norway', 'NO', 'Norwegian Krone', '', '', 'NOK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (164, 'Oman', 'OM', 'Omani Rial', '', '', 'OMR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (165, 'Pakistan', 'PK', 'Pakistan Rupee', '', '', 'PKR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (166, 'Palau', 'PW', 'US Dollar', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (167, 'Panama', 'PA', 'Panamanian Balboa', '', '', 'PAB', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (168, 'Papua New Guinea', 'PG', 'Papua New Guinea Kina', '', '', 'PGK', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (169, 'Paraguay', 'PY', 'Paraguay Guarani', '', '', 'PYG', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (170, 'Peru', 'PE', 'Peruvian Nuevo Sol', '', '', 'PEN', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (171, 'Philippines', 'PH', 'Philippine Peso', '', '', 'PHP', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (172, 'Pitcairn Island', 'PN', 'New Zealand Dollar', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (173, 'Poland', 'PL', 'Polish Zloty', '', '', 'PLN', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (174, 'Polynesia (French)', 'PF', 'CFP Franc', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (175, 'Portugal', 'PT', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (176, 'Puerto Rico', 'PR', 'US Dollar', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (177, 'Qatar', 'QA', 'Qatari Rial', '', '', 'QAR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (178, 'Reunion (French)', 'RE', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (179, 'Romania', 'RO', 'Romanian Leu', '', '', 'RON', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (180, 'Russia', 'RU', 'Russian Ruble', '', '', 'RUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (181, 'Rwanda', 'RW', 'Rwanda Franc', '', '', 'RWF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (182, 'Saint Helena', 'SH', 'St. Helena Pound', '', '', 'SHP', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (183, 'Saint Kitts & Nevis Anguilla', 'KN', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (184, 'Saint Lucia', 'LC', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (185, 'Saint Pierre and Miquelon', 'PM', 'Euro', '€', '&#8364;', 'EUR', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (186, 'Saint Vincent & Grenadines', 'VC', 'East Caribbean Dollar', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (187, 'Samoa', 'WS', 'Samoan Tala', '', '', 'WST', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (188, 'San Marino', 'SM', 'Italian Lira', '', '', 'ITL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (189, 'Sao Tome and Principe', 'ST', 'Dobra', '', '', 'STD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (190, 'Saudi Arabia', 'SA', 'Saudi Riyal', '', '', 'SAR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (191, 'Senegal', 'SN', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (192, 'Seychelles', 'SC', 'Seychelles Rupee', '', '', 'SCR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (193, 'Sierra Leone', 'SL', 'Sierra Leone Leone', '', '', 'SLL', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (194, 'Singapore', 'SG', 'Singapore Dollar', '$', '&#036;', 'SGD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (195, 'Slovakia', 'SK', 'Slovak Koruna', '', '', 'SKK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (196, 'Slovenia', 'SI', 'Slovenian Tolar', '', '', 'SIT', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (197, 'Solomon Islands', 'SB', 'Solomon Islands Dollar', '$', '&#036;', 'SBD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (198, 'Somalia', 'SO', 'Somali Shilling', '', '', 'SOD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (199, 'South Africa', 'ZA', 'South African Rand', '', '', 'ZAR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (200, 'South Georgia & South Sandwich Islands', 'GS', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (201, 'Spain', 'ES', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (202, 'Sri Lanka', 'LK', 'Sri Lanka Rupee', '', '', 'LKR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (203, 'Sudan', 'SD', 'Sudanese Dinar', '', '', 'SDD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (204, 'Suriname', 'SR', 'Surinam Guilder', '', '', 'SRG', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (205, 'Svalbard and Jan Mayen Islands', 'SJ', 'Norwegian Krone', '', '', 'NOK', '0', '0','','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (206, 'Swaziland', 'SZ', 'Swaziland Lilangeni', '', '', 'SZL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (207, 'Sweden', 'SE', 'Swedish Krona', '', '', 'SEK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (208, 'Switzerland', 'CH', 'Swiss Franc', '', '', 'CHF', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (209, 'Syria', 'SY', 'Syrian Pound', '', '', 'SYP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (210, 'Taiwan', 'TW', 'Taiwan Dollar', '$', '&#036;', 'TWD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (211, 'Tajikistan', 'TJ', 'Tajik Ruble', '', '', 'TJR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (212, 'Tanzania', 'TZ', 'Tanzanian Shilling', '', '', 'TZS', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (213, 'Thailand', 'TH', 'Thai Baht', '', '', 'THB', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (214, 'Togo', 'TG', 'CFA Franc BCEAO', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (215, 'Tokelau', 'TK', 'New Zealand Dollar', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (216, 'Tonga', 'TO', 'Tongan Pa&#699;anga', '', '', 'TOP', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (217, 'Trinidad and Tobago', 'TT', 'Trinidad and Tobago Dollar', '$', '&#036;', 'TTD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (218, 'Tunisia', 'TN', 'Tunisian Dollar', '$', '&#036;', 'TND', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (219, 'Turkey', 'TR', 'Turkish Lira', '', '', 'TRL', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (220, 'Turkmenistan', 'TM', 'Manat', '', '', 'TMM', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (221, 'Turks and Caicos Islands', 'TC', 'US Dollar', '$', '&#036;', 'USD', '0', '0', 'northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (222, 'Tuvalu', 'TV', 'Australian Dollar', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (223, 'U.K.', 'UK', 'Pound Sterling', '£', '&#163;', 'GBP', '0', '17.5','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (224, 'Uganda', 'UG', 'Uganda Shilling', '', '', 'UGS', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (225, 'Ukraine', 'UA', 'Ukraine Hryvnia', '', '', 'UAG', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (226, 'United Arab Emirates', 'AE', 'Arab Emirates Dirham', '', '', 'AED', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (227, 'Uruguay', 'UY', 'Uruguayan Peso', '', '', 'UYP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (228, 'USA Minor Outlying Islands', 'UM', 'US Dollar', '$', '&#036;', 'USD', '0', '0','','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (229, 'Uzbekistan', 'UZ', 'Uzbekistan Sum', '', '', 'UZS', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (230, 'Vanuatu', 'VU', 'Vanuatu Vatu', '', '', 'VUV', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (231, 'Vatican', 'VA', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (232, 'Venezuela', 'VE', 'Venezuelan Bolivar', '', '', 'BsF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (233, 'Vietnam', 'VN', 'Vietnamese Dong', '', '', 'VND', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (234, 'Virgin Islands (British)', 'VG', 'US Dollar', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (235, 'Virgin Islands (USA)', 'VI', 'US Dollar', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (236, 'Wallis and Futuna Islands', 'WF', 'CFP Franc', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (237, 'Western Sahara', 'EH', 'Moroccan Dirham', '', '', 'MAD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (238, 'Yemen', 'YE', 'Yemeni Rial', '', '', 'YER', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (239, 'Yugoslavia', 'YU', 'Yugoslav New Dinar', '', '', 'YUN', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (240, 'Zambia', 'ZM', 'Zambian Kwacha', '', '', 'ZMK', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (241, 'Zimbabwe', 'ZW', 'Zimbabwe Dollar', '$', '&#036;', 'ZWD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (242, 'Deutschland', 'DE', 'Euro', '€', '&#8364;', 'EUR', '0', '0','europe','1');";
